Fix thread '<unnamed>' panicked at 'assertion failed: self.is_char_boundary(n)'
Tried to load 1000 notices from the homepage and I found this error.

As some notices have prefixes to their titles such as "(재공지)[writer]" so `title.replace_range(0..dup.len(), "")` caused the error.